FROM docker:dind

RUN arch=$(arch | sed s/aarch64/arm64/ | sed s/x86_64/amd64/) && \
    wget https://storage.googleapis.com/minikube/releases/latest/minikube-linux-${arch}
RUN arch=$(arch | sed s/aarch64/arm64/ | sed s/x86_64/amd64/) && \
    install minikube-linux-${arch} /usr/local/bin/minikube

COPY . /home/$USER/k8s-playground

WORKDIR /home/$USER/k8s-playground

ENTRYPOINT ["dockerd-entrypoint.sh"]
