version: '3.7'

services:
  minikube:
    build: 
      context: .
      dockerfile: Dockerfile.dev
      args:
        - USER=$USER
    container_name: minikube-dind
    privileged: true
    restart: always
    network_mode: host
    volumes:
      - $HOME/Share:/home/$USER/Share
      - /var/run/docker.sock:/var/run/docker.sock
